[package]
name = "deep-flatten"
authors = ["Cryptex"]
description = "Useful utility for deep flattening nested Options."
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
